apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeuyrigafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skeuyrigafe
  template:
    metadata:
      labels:
        app: skeuyrigafe
    spec:
      containers:
      - image: okteto.dev/skeuyrigafe:latest
        name: skeuyrigafe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "08f35239-bba4-4603-ab54-f99002984cb8"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "08f35239-bba4-4603-ab54-f99002984cb8"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
